version: "3.6"

services:
        mariadb:
                container_name: mariadb
                build: requirements/mariadb
                image: mariadb:inception
                restart: always
                env_file: ./.env
                networks:
                        - inception-network
                volumes:
                        - mariadb-volume:/var/lib/mysql
        wordpress:
               container_name: wordpress
               build: requirements/wordpress
               image: wordpress:inception
               depends_on: [mariadb]
               restart: always
               env_file: ./.env
               networks:
                       - inception-network
               volumes:
                       - wordpress-volume:/var/html/www
        nginx:
               container_name: nginx
               build: requirements/nginx
               image: nginx:inception
               depends_on: [mariadb, wordpress]
               restart: always
               env_file: ./.env
               ports:
                       - "443:443"
               networks:
                       - inception-network
               volumes:
                       - wordpress-volume:/var/html/www
        proftpd:
               container_name: proftpd
               build: requirements/bonus/proftpd
               image: proftpd:inception
               depends_on: [wordpress]
               restart: always
               env_file: ./.env
               ports:
                       - "20:20"
                       - "21:21"
               networks:
                       - inception-network
               volumes:
                       - wordpress-volume:/wordpress


networks:
        inception-network: {}

volumes:
        mariadb-volume:
                driver_opts:
                        type: none
                        device: /home/bdetune/data/mariadb
                        o: bind
        wordpress-volume:
                driver_opts:
                        type: none
                        device: /home/bdetune/data/wordpress
                        o: bind

