version: "3.6"

services:
        mymariadb:
                container_name: mymariadb
                build: requirements/mariadb
                restart: always
                networks:
                        - db-network
#                volumes:
#                        - /home/bdetune/data:/var/run/mysqld

networks:
        db-network: {}
