version: "3.6"

services:
        mariadb:
                container_name: mariadb
                build: requirements/mariadb
                restart: always
                networks:
                        - db-network
                volumes:
                        - mariadb-volume:/var/lib/mysql
        wordpress:
               container_name: wordpress
               build: requirements/wordpress
               depends_on: [mariadb]
               restart: always
               networks:
                       - db-network
               volumes:
                       - wordpress-volume:/var/html/www

networks:
        db-network: {}

volumes:
        mariadb-volume:
                driver_opts:
                        type: none
                        device: /home/bdetune/data/mariadb
                        o: bind
        wordpress-volume:
                driver_opts:
                        type: none
                        device: /home/bdetune/data/wordpress
                        o: bind

