version: "3.6"

services:
        mariadb:
                container_name: mariadb
                build: requirements/mariadb
                image: mariadb:inception
                restart: always
                networks:
                        - db-network
                volumes:
                        - mariadb-volume:/var/lib/mysql
        wordpress:
               container_name: wordpress
               build: requirements/wordpress
               image: wordpress:inception
               depends_on: [mariadb]
               restart: always
               networks:
                       - db-network
                       - serv-network
               volumes:
                       - wordpress-volume:/var/html/www
        nginx:
               container_name: nginx
               build: requirements/nginx
               image: nginx:inception
               depends_on: [mariadb, wordpress]
               restart: always
               ports:
                       - "443:443"
               networks:
                       - serv-network
               volumes:
                       - wordpress-volume:/var/html/www

networks:
        db-network: {}
        serv-network: {}

volumes:
        mariadb-volume:
                driver_opts:
                        type: none
                        device: /home/bdetune/data/mariadb
                        o: bind
        wordpress-volume:
                driver_opts:
                        type: none
                        device: /home/bdetune/data/wordpress
                        o: bind

